metadata:
  name: "airflow-jobs"
  description: "Airflow job descriptor scripts"
  labels:
    public: false
    sensitive: false
    jira-project: "PEDSP"
    jira-board: 2877
    product: "Reporting and Insights"
    tier: "2"


  links:
    - &id001
      title: "README.md"
      url: "https://github.com/sindhu19460/cicd_hello_world_public_war/blob/main/README.md"
    - &id002
      title: "RUNBOOK.md"
      url: "https://github.com/sindhu19460/cicd_hello_world_public_war/blob/main/RUNBOOK.md"
links:
  - *id001
  - *id002
spec:
  owner: "cg-dsp-operational-reporting-data"
  type: "pipeline"
  lifecycle: "production"
