metadata:
  name: "airflow-jobs"
  description: "Airflow job descriptor scripts"
  labels:
    public: false
    sensitive: false
    jira-project: "PEDSP"
    jira-board: 2877
    product: "reporting and insights"
    tier: "2"
  links:
    # - title: "runbook"
    #   url: "https://github.com/sindhu19460/cicd_hello_world_public_war/blob/main/README.md"

spec:
  owner: "cg-dsp-operational-reporting-data"
  type: "pipeline"
